---
  - hosts: vagrant-machine
    tasks:
      - name: just pinging
        ping: ~
      
      - name: Update APT package manager repositories cache
        become: true
        apt:
          update_cache: yes
      
      - name: Upgrade installed paclages
        become: true
        apt:
          upgrade: safe

      - name: Install cowsay - it's probably important
        become: true
        apt:
          name: cowsay