---
  - hosts: vagrant-machine
    tasks:
      - name: just pinging
        ping: ~

      # - name: Upgrade installed packages
      #   become: true
      #   apt:
      #     upgrade: safe

      - name: Add PHP 7 PPA repository
        become: true
        apt_repository:
          repo: 'ppa:ondrej/php'
      
      - name: Install LEMP packages
        become: true
        apt:
          name: "{{ item }}"
          state: latest
          update_cache: yes
        with_items:
          - cowsay
          - php7.2-cli
          - php7.2-curl
          - php7.2-fpm
          - php7.2-intl
          - php7.1-mysql
          - nginx
          - mysql-server
          - git